"""Gemini-based semantic annotation for discovered pages."""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass

from game_agent.cognition import prompts
from game_agent.cognition.gemini_client import GeminiClient
from game_agent.perception.state import L1Perception, L2Perception

logger = logging.getLogger(__name__)


@dataclass
class PageAnnotation:
    """Semantic metadata for a game page, generated by Gemini."""

    page_name: str
    page_description: str
    page_category: str
    key_buttons: list[str]


class PageAnnotator:
    """Uses Gemini to semantically label newly discovered pages."""

    def __init__(self, gemini: GeminiClient) -> None:
        self._gemini = gemini

    def annotate(self, perception: L1Perception) -> PageAnnotation:
        prompt = prompts.ANNOTATION_PROMPT.format(
            poco_tree_markdown=perception.poco_tree_markdown
        )
        response = self._gemini.single_prompt(
            prompt,
            log_context="page_annotation",
        )
        return self._parse_annotation(response.text)

    def annotate_with_screenshot(self, perception: L2Perception) -> PageAnnotation:
        prompt = prompts.ANNOTATION_WITH_SCREENSHOT_PROMPT.format(
            poco_tree_markdown=perception.poco_tree_markdown
        )
        response = self._gemini.send_multimodal(
            prompt,
            perception.screenshot_b64,
            log_context="page_annotation_with_screenshot",
        )
        return self._parse_annotation(response.text)

    def _parse_annotation(self, text: str | None) -> PageAnnotation:
        if not text:
            return PageAnnotation(
                page_name="未知页面",
                page_description="页面标注失败",
                page_category="未知",
                key_buttons=[],
            )
        try:
            cleaned = text.strip()
            if cleaned.startswith("```"):
                cleaned = cleaned.split("\n", 1)[1].rsplit("```", 1)[0]
            data = json.loads(cleaned)
            return PageAnnotation(
                page_name=data.get("page_name", "未知页面"),
                page_description=data.get("page_description", ""),
                page_category=data.get("page_category", "未知"),
                key_buttons=data.get("key_buttons", []),
            )
        except (json.JSONDecodeError, KeyError) as exc:
            logger.warning("解析页面标注 JSON 失败：%s", exc)
            return PageAnnotation(
                page_name="未知页面",
                page_description=text[:200] if text else "",
                page_category="未知",
                key_buttons=[],
            )
